### ISSUE TITLE
Adding Simple CSS Fade-in Animation on Load

### ISSUE THREAD

**Issue by Rishav13773** [therealtmmy/Quotes-Generator#12]
I'd like to contribute to this amazing open-source project by adding a simple CSS fade-in animation on page load. This animation will enhance the user experience and add a touch of elegance to the website's elements.

Description:
Currently, when the website loads, the content appears abruptly without any animations. I propose adding a smooth fade-in effect to elements upon page load to create a more visually appealing transition.

Proposed Solution:
To achieve the desired fade-in effect, we can use CSS animations and transitions. By applying the appropriate CSS classes, we can control the timing and duration of the fade-in animation.

**Comment by therealtmmy** [comment]
That's a great one. Please feel free to contribute to this project

**Comment by therealtmmy** [comment]
Thank you for your commit
